### ISSUE TITLE
Play_DQN.py가 제대로 작동하지 않습니다.

### ISSUE THREAD

**Issue by BlueMelon715** [jcwleo/Reinforcement_Learning#1]
학습시킨 ckpt를 이용하여 Play_DQN.py로 play 해보려했는데 게임은 진행되지만 e-greedy 때문인지 agent가 학습된 대로 움직이지 않아서 점수가 매우 낮게 play 됩니다.

**Comment by jcwleo** [comment]
수정했습니다. 늦게봐서 죄송합니다.

**Comment by BlueMelon715** [comment]
괜찮습니다. 확인했습니다.
